---
title: Prey item and pesticide effect survey 2020
output:
    rmdformats::readthedown:
      collapsed: false
      highlight: kate
---

```{r setup, include=FALSE}
library(XLConnect)
library(ggplot2)
library(dplyr)
```


```{r}
active <- readWorksheetFromFile("Raw Data/Arthropod_data.xlsx", "Active")
```

# Sampling summary

```{r}
active$repID <- paste(active$site, active$month, active$day, active$microsite, active$rep)
active$month <- gsub(" ","", active$month)

summary <- active %>% group_by(site, month, microsite, method) %>% summarise(n_distinct(rep))

summary <- summary %>% ungroup() %>% mutate(month_num = case_when(month == "July" ~ 1, month == "Aug" ~ 2, month == "Sept" ~ 3))
summary <- summary %>% ungroup()

summary <- summary[order(summary$site, summary$month_num, summary$method, summary$microsite),]

count(summary, site)
summary <- rename(summary, samples = "n_distinct(rep)")
summary <- select(summary, -month_num)
```


Number of samples (not specimens)
```{r}
sum(summary$samples)
knitr::kable(summary)
```

Summary stats for sweep net specimens
```{r}
active$quantity <- as.numeric(active$quantity)
sum(active$quantity, na.rm = TRUE)
order <- active %>% group_by(order) %>% summarise(sum = sum(quantity, na.rm = TRUE))
ggplot(order, aes(sum, order)) + geom_bar(stat = "identity")

```



```{r}
#calculations for mark

active <- active %>% group_by(order) %>% summarise(abun = sum(as.numeric(quantity), na.rm = TRUE))

pits <- readWorksheetFromFile("Raw Data/Arthropod_data.xlsx", "Pitfalls")
pitcount <- pits %>% group_by(order) %>% summarise(abun = sum(as.numeric(quantity), na.rm = TRUE))

mal <-readWorksheetFromFile("Raw Data/Arthropod_data.xlsx", "Malaise")
malcount <- mal %>% group_by(order) %>% summarise(abun = sum(as.numeric(quantity), na.rm = TRUE))
  
  
write.csv(malcount, "malcount.csv")
write.csv(pitcount, "pitcount.csv")
write.csv(active, "active.csv")

ants <- pits %>% filter(family == "Formicidae")
sum(ants$quantity)
```